In [10]:
import numpy as np
import pandas as pd

In [11]:
from sklearn.datasets import load_iris


In [13]:
iris = load_iris()
df_iris = pd.DataFrame(data=iris.data, columns=iris.feature_names)

In [14]:
y = iris.target
X = df_iris

In [15]:
rgen = np.random.RandomState(42)

In [28]:
w_ = rgen.normal(loc=0.0, scale=0.01, size=1 + X.shape[1])
cost_ = []

In [37]:
X[2:3].values

array([[4.7, 3.2, 1.3, 0.2]])

In [58]:
np.dot(X[:100].values,w_[1:])+w_[0]

array([-0.05015347, -0.05043183, -0.04710316, -0.05070595, -0.04944578,
       -0.05977249, -0.04979171, -0.05184299, -0.04834514, -0.05037823,
       -0.05298002, -0.05282481, -0.04824118, -0.04017269, -0.04837721,
       -0.05613331, -0.05211937, -0.05187839, -0.05968672, -0.05306579,
       -0.05753247, -0.05503267, -0.03992974, -0.06155199, -0.05856465,
       -0.05472412, -0.0572061 , -0.05253248, -0.05086117, -0.052843  ,
       -0.05355069, -0.05715574, -0.04935579, -0.05032266, -0.05210314,
       -0.04658707, -0.05010311, -0.04725513, -0.0461899 , -0.05230872,
       -0.04949938, -0.05007428, -0.04570597, -0.06041398, -0.06244382,
       -0.05169101, -0.05325415, -0.04855071, -0.05251429, -0.05017167,
       -0.14356549, -0.13866947, -0.1488932 , -0.12363932, -0.14201633,
       -0.13292737, -0.14351325, -0.10203527, -0.13879026, -0.12108592,
       -0.10729541, -0.1310849 , -0.12103518, -0.14009981, -0.11500016,
       -0.13667042, -0.13542755, -0.12080719, -0.14015763, -0.11

In [59]:
error = y[:100]-(np.dot(X[:100].values,w_[1:])+w_[0])
error

array([0.05015347, 0.05043183, 0.04710316, 0.05070595, 0.04944578,
       0.05977249, 0.04979171, 0.05184299, 0.04834514, 0.05037823,
       0.05298002, 0.05282481, 0.04824118, 0.04017269, 0.04837721,
       0.05613331, 0.05211937, 0.05187839, 0.05968672, 0.05306579,
       0.05753247, 0.05503267, 0.03992974, 0.06155199, 0.05856465,
       0.05472412, 0.0572061 , 0.05253248, 0.05086117, 0.052843  ,
       0.05355069, 0.05715574, 0.04935579, 0.05032266, 0.05210314,
       0.04658707, 0.05010311, 0.04725513, 0.0461899 , 0.05230872,
       0.04949938, 0.05007428, 0.04570597, 0.06041398, 0.06244382,
       0.05169101, 0.05325415, 0.04855071, 0.05251429, 0.05017167,
       1.14356549, 1.13866947, 1.1488932 , 1.12363932, 1.14201633,
       1.13292737, 1.14351325, 1.10203527, 1.13879026, 1.12108592,
       1.10729541, 1.1310849 , 1.12103518, 1.14009981, 1.11500016,
       1.13667042, 1.13542755, 1.12080719, 1.14015763, 1.11825801,
       1.14725541, 1.12522389, 1.14755059, 1.13689193, 1.13211

In [62]:
(X[:100].values.T).dot(error)*0.01

array([3.48663781, 1.65533822, 2.44808722, 0.75679821])

In [61]:
(error*0.01).sum()

np.float64(0.590912642913334)