In [24]:
import numpy as np

In [25]:
rgen = np.random.RandomState(42)
rgen

RandomState(MT19937) at 0x7FA2103EEE40

In [26]:
w_ = rgen.normal(loc=0.0, scale=0.01, size=1+4)
w_

array([ 0.00496714, -0.00138264,  0.00647689,  0.0152303 , -0.00234153])

In [27]:
X = np.array([2,3,2,2,])
X

array([2, 3, 2, 2])

In [33]:
np.dot(X, w_[1:])+w_[0]

0.047410041283403204

In [35]:
ubdate = np.where(np.dot(X, w_[1:])+w_[0]>=0, 1,-1)

array(1)

In [36]:
w_[1:]*X

array([-0.00276529,  0.01943066,  0.0304606 , -0.00468307])